marcells/node-build-monitor

- app/services/Jenkins.js
Jenkins frequently returns empty action items as part of previous builds (I still haven't identified why), but these empty blocks cause node to crash with the following error:
TypeError: Cannot read property 'causes' of null
at getRequestedFor (/build-mon/app/services/Jenkins.js:51:31)
at simplifyBuild (/build-mon/app/services/Jenkins.js:72:31)
at /build-mon/app/services/Jenkins.js:14:33
at Request._callback (/build-mon/node_modules/jenkins-api/lib/main.js:139:17)
at Request.self.callback (/build-mon/node_modules/request/request.js:373:22)
at Request.emit (events.js:98:17)
at Request.<anonymous> (/build-mon/node_modules/request/request.js:1318:14)
at Request.emit (events.js:117:20)
at IncomingMessage.<anonymous> (/build-mon/node_modules/request/request.js:1266:12)
at IncomingMessage.emit …
> Fixed issue with empty actions in Jenkins crashing the app

- README.md
- app/services/Jenkins.js
- package.json
This PR allows users to configure the jenkins API calls using the new version of the jenkins-api module. For example, one can configure the jenkins service to switch off the strictSSL like this:
{
"name": "Jenkins",
"configuration": {
"url": "https://ci-openpaas.linagora.com/jenkins",
"job": "openpaas-rse-oncommit",
"options": {
"strictSSL": false
}
}
}
The options in jenkins-api follows the request module options.
Cheers,
Christophe
> Update to jenkins-api 0.2.6 to add options on HTTP requests

- README.md
- app/services/GitLab.js
This is an opinionated GitLab-plugin, which I'm currently working on. I might still fix and tweak this according to the upcoming real use experiences, but since there's been interest in a GitLab-plugin, I wanted to share this already.
My use-case is a local GitLab installation with currently about 1k repositories. Yet, because we are usually working with only a small portion of the at the same time, we should manage with a single monitor showing all the current and failing builds.
The complexity in the plugin comes from the current GitLab API, which requires to poll individual repositories for new builds.
Possibly fixes https://github.com/marcells/node-build-monitor/issues/2
```
...
"services": [
{
"name": "GitLab",
"configuration": {
"url": "https://gitlab...",
"token": "..."
}
}
]
... …
```
> Add initial opinionated GitLab-plugin implementation

- app/services/GitLab.js
We've been running GitLab-integration 24/7 since the first implementation. I'll try to provide fixes when I remember. This fix issue where integration didn't update projects that were known to have builds disabled, but whose builds were turned on.
As a recap, we are running a monitor against GitLab with about 1k repositories and want it to automatically choose jobs with builds. Therefore all the optimization to not constantly poll all the repos. (And different monitors are customized simply by limiting GitLab token permissions and keeping node-build-monitor config simple.)
> Fix GitLab issue where know projects were not updated once builds were enabled

- README.md
- app/services/GitLab.js
You can now configure the porjects displayed for gitlab by providing an array of slugs, for example:
```json
"slugs": [
"gitlab-org/gitlab-ci-multi-runner",
"gitlab-org/release-tools"
]
```
> extend gitlab config to support project selection

- app/services/GitLab.js
```
/Projects/node-build-monitor/app/services/GitLab.js:334
if (self.config.slugs.indexOf('*/*') > -1 || self.config.slugs.indexOf(project.path_with_namespace) > -1) {
^
TypeError: Cannot read property 'indexOf' of undefined
at updateProject (/Projects/node-build-monitor/app/services/GitLab.js:334:30)
at /Projects/node-build-monitor/app/services/GitLab.js:391:21
at /Projects/node-build-monitor/node_modules/async/lib/async.js:356:13
at iterate (/Projects/node-build-monitor/node_modules/async/lib/async.js:262:13)
at async.forEachOfSeries.async.eachOfSeries (/Projects/node-build-monitor/node_modules/async/lib/async.js:281:9)
at _asyncMap (/Projects/node-build-monitor/node_modules/async/lib/async.js:355:9)
at Object.mapSeries (/Projects/node-build-monitor/node_modules/async/lib/async.js:347:20 …
```
> App crashes when slugs key is missing in config.json for Gitlab Service

- Gruntfile.js
- app/services/GitLab.js
- package.json
I started digging through code, b/c by default GitLab integration doesn't work for me, in the log I saw only that parser detect 0 projects.
OFC it's a first step, b/c there is a lot more work to do, i.e. I'd remove `async` lib, b/c it doesn't work as expected. I tried to follow docs and even simplest things like callback params work in a different way, i.e. I got boolean instead of an array with data 🤷‍♂️ 
Are you interested in this type of changes or should I just maintain an own fork with custom version?
PS. Tests are failing, b/c I used few ES6 features.
> Fixed GitLab support

- app/services/GitLab.js
We have multiple projects in a single group, and we add projects based on different components.  Instead of having to update the config file, pull it into our Docker container, and restart each time we add a new project, it would be easier to specify just the group name followed by /* to get all the projects in the group to automatically populate on the build monitor.  
I am just pulling the information out of the same JSON response, but looking for a match on the namespace name and /* in addition to looking for the exact name match or default (*/*).
> All Gitlab projects in a namespace specified with a single slug

- .gitignore
- README.md
- app/services/BuddyBuild.js
- test/services/BuddyBuild.js
If a user token has multiple buddy build apps (ios / andriod for different envs like dev / staging / prod etc as in my case), today you'll have to specify each app as a different service. However, thats we can simplify that by first fetching all the builds and then iterate over them to get latest build for each.
Kindly accept the MR if you think it makes sense
> Ability to pull multiple BuddyBuild apps instead of having to specify each one as a separate service

- .gitignore
- README.md
- app/services/GitLab.js
* Versions of Gitlab > 9 provide a new API V4, the old API V3 will be
deprecated with one the next 9.x versions.
* Besides of renamed member fields (builds are now called jobs), the new
API will retrieve a lot more projects.
* Therefore a new config field `additional_query` is introduced which
may be used to filter the jobs list beforehand.
> Update Gitlab.js to use API V4

- app/services/GitLab.js
1. Builds are reduced based on timestamp instead of pipeline.
2. Return pipeline status instead of job status.
Build monitor should show the status of the pipeline and not the job. Job level status must be a secondary level of information.
> Fixed issues in gitlab

- app/monitor.js
- app/requests.js
- app/services/TeamCity.js
Bugs fixed : 
- NTLM work made it a requirement to add auth to teamcity service configuration which doesn't need to be mandatory.
- Refactor of getRequest led to the incorrect url being passed in the teamcity makeRequest call.
- Refactor of getRequest added auth to the "default" getRequest. Have removed it as doesn't work.
- Occasional issues of trying to get the latest commit caused the app to blow up. There is now protection against this.
- Previously the "LatestBuildOnly" would just grab the top build with no guarantee it is the latest build. Now we sort before shifting.
> Fixing broken TeamCity service

- app/services/GitLab.js
This will fix https://github.com/marcells/node-build-monitor/issues/65
> defensive programming: don't freak out if a job has no associated commit

- README.md
- app/services/GitLab.js
This pull request adds a new configuration option called `numberOfPipelinesPerProject` to the GitLab service config, allowing the user to specify the maximum number of pipelines (builds) to fetch for a single project.
This will allow users to select a group of repositories (e.g., all repositories that are owned by the user corresponding to the key that the GitLab API is called with) and specify that the build monitor should show only X builds per project. When the builds are sorted by IDs (which is the case right now), this ensures that only the most recent X builds appear on the CI display. In our case, we use it with X=1 to show only the most recent build for a group of repositories being monitored.
> added numberOfPipelinesPerProject option to GitLab service config

- README.md
- app/services/Jenkins.js
This pull request adds a single-view mode to the Jenkins service.
Currently the Jenkins service is capable of displaying all the builds from a single Jenkins job only. The pull request allows the user to specify the name of a single Jenkins *view* instead, and the service will fetch the builds of all the jobs that are part of the given Jenkins view instead. This way an organization can simply collect the jobs that should be shown on the build monitor into a single view, configure the build monitor to show this view only, and then add new projects to the build monitor later simply by updating the Jenkins view. (There is also no need to repeat the Jenkins credentials once for every job in the build monitor config).
> Jenkins: added single-view mode that shows all jobs from a Jenkins view

- app/services/GitLab.js
There was a bug in the `getBuilds()` function of the GitLab service, which resulted in the callback not being called at all when the list of projects was not loaded from GitLab yet. This typically happened at startup. As a result, one had to wait until the next check _after_ the loading of the project list has completed before the builds appeared on the screen.
This PR fixes the bug by ensuring that `getBuilds()` calls its callback in both cases, i.e. when `self.projects.length === 0` and when `self.projects.length !== 0`.
> GitLab: getBuilds() did not call its callback when the projects were not loaded yet -- now it does

- app/public/scripts/BuildViewModel.js
- app/services/GitLab.js
As discussed in #26: this PR adds support for forwarding branch and commit-related information from the GitLab service to the BuildViewModel. Other build services could be updated in a similar manner where such a change makes sense.
The themes are not updated yet so branches and commit hashes are not shown on the displays yet - one has to develop a custom theme for that.
> GitLab service can now provide branch and commit information to the BuildViewModel

- app/services/GitLab.js
At the moment the project name is used to compare with the namespace path. If the name contains whitespaces, the path does not match against the name.
The fix uses the path property.
> Compare namespace path with project path

- README.md
- app/services/GitLab.js
Implemented double asterisk in gitlab slugs for subgroups wildcard support as discussed in  #93
> Double asterisk support in gitlab slugs - include nested projects

- app/services/GitLab.js
Due to the recent merge of #91, the GitLab config parameter 'numberOfPipelinesPerProject' is no longer optional. With this pull request, the parameter will be optional again.
> GitLab: config.numberOfPipelinesPerProject is optional

- app/public/scripts/main.js
When running node-build-monitoring behind a proxy with a subfolder rewrite, the absolute path is a problem.
> Use relative path for socket.io

- app/app.js
- app/public/scripts/AppViewModel.js
- app/public/scripts/BuildMonitorServer.js
- app/public/scripts/knockoutExtensions.js
- app/public/scripts/main.js
- app/public/stylesheets/base/style.css
- app/views/index.pug
- app/views/layout.pug
This PR adds support for running node-build-monitor in proxies in a subfolder, for example localhost/foobar/.
It fixes asset loading (JS, CSS and images) as well as socket.io path.
It can be tested with the following `docker-compose.yml` file:
```
version: '3'
services:
node-build-monitor:
build: .
ports:
- "3000:3000"
labels:
- "traefik.frontend.rule=PathPrefixStrip:/foobar/"
proxy:
image: traefik
command: -c /dev/null --web --docker --docker.exposedbydefault=true
ports:
- "80:80"
- "8080:8080"
volumes:
- /var/run/docker.sock:/var/run/docker.sock
```
Then you can verify that things work on http://localhost:3000 and http://localhost/foobar/
> Fix relative path for socket.io

- app/services/Tfs.js
Sometimes TFS doesn't respond with the 'requestedFor' value. (Mostly scheduled/automatic builds) Don't prevent the entire build from displaying if thats the only part we are missing.
> Sometimes TFS doesn't respond with the 'requestedFor' value.

- app/public/scripts/BuildViewModel.js
- app/services/Tfs.js
In theory this shouldn't break VSTS, but I've only got TFS On Premise to test with.
All I've really done is made queued builds not show up as blue/running and rejiged the colors/statuses a bit, so they actually match the docs, and aren't mixed and matched. (it was doing my head in!)
Also, sorry about the multiple commits to fix the tabs, please squash those!
> Tfs changes

- README.md
- app/services/Bamboo.js
Hi,
Please help to review my PR to add 2 additional states to Bamboo monitoring. Previously Bamboo is checking res.state which only returns either Successful or Failed. To check for additional states, I need to look into lifeCycleState
I also update isRunning to reverse of whether the buildCompletedTime is available. This is so that when sorting by date, in-progress/stopped state will be sorted according to start time
Many thanks
Best regards,
> add in progress and stopped states to bamboo service

- app/monitor.js
- app/services/Bamboo.js
Hi,
Could you help to review a minor change in bamboo in-progress background color?
Before this change, in-progress status has yellow background and white text color which makes the text very difficult to see
I change the color to dark orange so that it looks ok even with white text color
This is just a quick workaround. In my opinion, a proper fix should be decoupling status of the build with text/background colors. E.g. define a common set of status that all services can return (in-progress, success, fail...) and in BuildViewModel, determine the proper color depending on the status. Optionally each service can return different background/text color to override the default colors. However this change can be quite major and affect all the services, so not sure what's the best way to do …
> change in-progress background color for bamboo service

- README.md
- app/services/Bamboo.js
Hi,
Please help to review my PR
As per your suggestion, I add a new setting `latestBuildPerBuildPlanOnly` to Bamboo service to restrict number of result returned from Bamboo server
Thanks
> add latestBuildPerBuildPlanOnly to Bamboo service

- app/services/GitLab.js
Clears the internal project collection in gitlab plugin forces it to query for new projects at the refresh interval
> Issue130-Gitlab plugin doesn't add new builds once running

- app/services/Tfs.js
If you have multiple config entries that return overlapping builds, then you can end up with duplicate tiles shown due to some fields being different between the first API call and the next.
Specifically for TFS, the finishedAt time is returned as the current time of the call if the build is still running. This means that when the ETag is generated it makes both builds as unique, when it shouldn't, due to the finishedAt time being different.
I did it this way because I was thinking about making it generic... but while i'm writing this, I think it probably actually makes more sense to just change the `finishedAt: build.finishTime ? new Date(build.finishTime) : new Date(),` to `finishedAt: build.finishTime ? new Date(build.finishTime) : '',` in the TFS.js service.
Thoughts ?
> Prevent duplicate TFS builds

- README.md
Rename VSTS to Azure DevOps. Also fixes documentation for Azure DevOps release service
> Rename VSTS to Azure DevOps

- app/requests.js
Better error handling and try/catch for unhandled exceptions like ECONNRESET
Fixes #100 probably
> Better error handling and try/catch

- README.md
- app/monitor.js
We need the date ordering, but the failed builds / test runs should have prio in the ordering over the succeeded once. We need this so that we can react and handle build/test errors as fast as possible.
> Add errorsFirst option for sorting

- app/services/Tfs.js
Change allowed api versions from 2.0 only to 2.0, 4.1.
Enables use of "maxBuildsPerDefinition" in the queryParam. Other new params also available.
Tested against TFS 2018 on-prem.
> Enable support for tfs api version 4.1

- README.md
- app/services/TfsRelease.js
This will add the feature to group builds having the same release id.
Given a release is deployed on multiple environments where one deployment (for the same release) fails:
It is currently handled on per build basis (`release.id`) instead of grouped builds by release (`release.release.id`) basis:
> Add feature to group builds having the same release id

- README.md
- app/services/TeamCity.js
Hi - 
I made a simple change to report TeamCity builds which have failed to start as build failures themselves.  We usually encounter this when a dependency fails for some reason -- if that dependency is not itself being monitored (because there are a lot of them, for example), then the build monitor still looks 'green' without this flag.  We'd prefer an indication that the pipeline has failed somewhere, without needing to track each step individually.
I introduced an option 'reportFailedToStart' to optionally enable this behavior.  
As far as testing, I ran it through grunt, as well as manual testing through our TeamCity instance.  
Let me know what you think, and thanks for the project!
> Optionally report TeamCity builds which have failed to start as build failures

- README.md
- app/services/Drone.js
As DroneCI 1.0 breaks the compatibility with [drone-wall](https://github.com/drone/drone-wall), I think that's the occasion to allow Drone user to migrate to this project.
I created this service to request the Drone > 1.0 API.
One improvement I plan for soon is to listen the /stream endpoint to listen for change instead of doing the requests every X seconds. But this needs some deeper changes, so I prefer to submit two separate Pull Requests.
> Add a Drone CI service

- app/public/scripts/OptionsViewModel.js
- app/public/stylesheets/themes/twenty/style.css
- app/public/templates/themes/twenty.html
This theme is based on the default theme, but more condensed to be able to see 20 tiles on a 1920x1080 screen in full screen mode.
I also moved the "times" section into the bottom row in order to get more space for displaying the build status when builds are in progress.
> add new theme "twenty" to support displaying 5x4 tiles on a 1920x1080 screen

- app/services/Bitrise.js
This PR includes the PR author as the `requestedFor` build attribute. This information is available whenever a build is triggered for a pull request. Alternatively, it will include the triggered_by information, which is only really useful when the build is manually triggered.
It also includes the branch being built in the same field.
It also shows the triggered workflow as the reason. It is a more useful information than the previous "push" string for webhook builds.
> Bitrise author, branch and workflow info

- README.md
- app/requests.js
- app/services/TfsRelease.js
Relax the API restriction to when releases were first available via the API (2017 Update 2)
(I decided to leave my error handling in there, so its easier in the future to work out why TFS rejected an API call, but I can remove it if required.)
EDIT:
Also fixed the startTime field always being populated with the queuedTime of the Release, when the startTime field should have been used instead)
> TfsRelease - Support API version 3.2-preview

- app/services/Drone.js
DroneCI reports failed builds with a status of 'error' or 'failure'
> Report failures as errors

- app/services/Tfs.js
This fixes a TFS 2019 (and probably 2018) bug, where multiple build Statuses were incorrectly shown, as getLatestBuildStep wasn't correctly filtering TimelineRecords of type Task.
(For some reason Microsoft has made the TimelineRecord.Type field a String ... so I couldn't create an enum style list like the others)
This should still work for 2017, although now that we (finally) upgraded, I don't really have a way to fully test this, outside just assuming Microsoft haven't touched the version 2.0 API call in 2019.
> Fix Build steps displaying incorrectly for TFS 2019

- app/services/BitbucketPipelines.js
Paused BitBucket pipelines were shown as `in progress`. This PR shows them as color grey & status `Paused`.
> feat: support BitBucket paused pipelines

- app/services/Tfs.js
I probably should have commited this a while ago :(
Specifically in TFS/Azure DevOps 2020, the API limiting 'CircuitBreaker' seems a little more picky on how often things are called.
So, while researching ways to increase this limit - it occurred to me, that we really don't need to get build steps for ones that have already finished running.
This resulted (for me) in significantly less calls to the API - going from 14 per refresh down to at most 4.
(Based on only showing 12 builds or releases on screen at one time)
> Reduce calls to TFS server when showBuildStep is enabled
