marcells/node-build-monitor

test/monitor.js

I reworded some testcases to fit within the "describe something... it should ..." pattern for improved readability.

Reworded tests

---

app/public/scripts/OptionsViewModel.js
app/public/stylesheets/themes/stoplight/style.css
app/public/templates/themes/stoplight.html

More intended as another theme example than hoping to merge the pull-request.
Just shows off alternate lay-over, we use something we call "detailed stoplight" ordered in a different way. This is more customized to our layout needs where project is listed before build number.
I won't be insulted if closed as "won't merge" ;)

Add new theme: stoplight

---

app/services/Bamboo.js

I had an issue with a non existing underscore-lib. So I decided to cut it out and use native v8/ECMAScript-stuff

remove unnecessary dependency on underscore

---

README.md
app/services/GitLab.js

1. Added the ability to optionally filter the build by branch.
2. Rewrote the gitlab service to be similar to other services.

Gitlab: filter by branch

---

README.md

Visual Studio Online was renamed to Visual Studio Team Services some time ago

Replace Visual Studio Online with Visual Studio Team Services

---

README.md
app/requests.js
app/services/TeamCity.js
app/services/Tfs.js
app/services/Tfs2015.js
app/services/TfsProxy.js
package.json

I have added support for ntlm to the CI's that could support it.  There wasn't any way to plug it into request so it's if branched

Add ntlm support

---

Dockerfile

To auto reload config.json when made some change in the file.
Thanks for the node-build-monitor

Dockerfile, forever with watch to config file

---

README.md
app/services/Tfs.js
app/services/TfsRelease.js
app/services/VstsReleases.js

- Edited the Tfs.js module in which some of the statuses were missing (double checked them with the Api).
- Added new module for the releases in VSTS and TFS (the Api should be the same).
- Updated the Readme with the new module and a sample how to use it.

VSTS Release Module and fixes in TFS Module

---

README.md

Documentation has been updated to correct the URL provided for reference. Mandatory nature of the fields is also mentioned.
#110

docs: update documentation for Tfs service

---

README.md
app/services/Tfs.js

In theory the last thing :)
A request I got asked for at work, was to add the current builds Stage/Step, and I thought other people might find it useful too.
This only applies to inProgress builds, as it doesn't make much sense otherwise.
eg.

Add TFS Build Stage/Steps

---

app/services/GitLab.js

added handling for manual step discused in [#118]( https://github.com/marcells/node-build-monitor/issues/118)

added handling for manual step in gitlab-ci config

---

app/monitor.js
package.json

Allow latestBuildOnly to be defined at the service level and have it override the global setting.

latestBuildOnly setting at the service level

---

app/requests.js

eg. 401 Unauthorised because our PAT has expired!

Gives the user a little more feedback if the web request fails.

---

README.md
app/services/TeamCity.js

Use "guestAuth" endpoint in TeamCity.js when "useGuest" configuration property is enabled.

Add "useGuest" to configuration at TeamCity Configuration.

---

README.md
app/services/CCTray.js
package.json

Adding support for CCTray as per Issue #120 .

Add support for CCTray

---

app/services/TeamCity.js

Property was not filled, only the coloring was implemented

Fill also the property hasErrors at TeamCity interpretation

---

app/services/Buildkite.js

This fixes a bug which causes the node-build-monitor to crash unexpectedly.
This is caused due to no "builds" being returned by buildkite. The fix is to just stub out the required information.

fixed undefined crash when pipeline has no builds

---

app/services/TfsRelease.js

Hi,
Long time no see. :)
I've created a fix for the new grouping feature of TFSRelease. There where 2 problems:
- The status was never updated correctly, if the release was already in the list, meaning, none of the changes were correctly applied.
- If there are more sub environment releases under the TFS Release Definition, the last one was taken. I've rewritten the whole thing from scratch, now it's doing a group by deploymentid and a priority sort, to get the relevant status out of the sub steps of a release.
I've tested it but please also take a look.
Cheers

Fix TFSRelease grouping

---

README.md
app/services/Shippable.js

Added support for [Shippable](https://www.shippable.com) CI. Let me know if something should be changed.

Added Shippable CI support

---

README.md
app/services/PRTG.js

Hey Marcell,
This PR is a new extension for the build monitor. You can now add Sensors from PRTG monitoring service to the list.
Best,
Alea

Add PRTG monitoring service support

---

README.md

Add PRTG to overview of supported services

Add PRTG to overview of supported services

---

app/services/PRTG.js

Sorry, I left a test link in the code.

Fix PRTG link

---

README.md
app/services/CircleCI.js
package.json
test/services/CircleCI.js
yarn.lock

Hello there,
in addition to Drone, as we use CircleCI too I created a service for that CI provider.
It is slightly more complex as CircleCI has a concept of job (a simple task) and a concept of workflow (a sequence of tasks to execute).
As the CircleAPI only provides the job data, I had to code something to deduct the workflow statuses in order to merge multiple jobs in a single workflow build item.

Add a CircleCI service

---

app/services/Tfs.js

Also add additional logging to determine what fault might be occurring.
Should fix #178

TFS: Rework the async callback for getting buildSteps

---

README.md
app/services/TfsRelease.js

Optional protocol in config for #193

---

README.md
app/services/BambooDeploy.js

Support for [BambooDeploy](https://www.atlassian.com/software/bamboo) deployment service to display the deployment status.

Display deployment status for Bamboo deploy

---

app/services/Drone.js

Fixes https://github.com/marcells/node-build-monitor/issues/213

Bug: Drone builds are not filtered by both branch and event

---

app/services/Drone.js
test/services/Drone.js

Fixes #219 
Primarily tests the filtering functionality. I end up testing by accident the api uri and service configuration. through the filtering tests. I'm not checking error handling (other than I don't get errors from my mocked server).

Adds Unit Tests for Drone Service & Fixes a bug in filtering

---

test/services/Drone.js

Not sure how I didn't catch them. Sorry!

Fixes linting errors

---

app/services/GitLab.js
test/services/GitLab.js

Color is same as jenkins. Should look similar to (I removed ou specific values):

first attemp to fix #228

---

Dockerfile

Update Dockerfile base image 
